theme: jekyll-theme-hacker

title: W. Kubinski
description: Reactor Physics | Optimization | Machine Learning

logo: wkubinski.jpg

show_downloads: false
github:
  is_project_page: false

plugins:
 - jekyll-seo-tag
