theme: jekyll-theme-minimal

title: Wojciech Kubinski
description: Nuclear Physicist | Reactor Physics | Optimization | Machine Learning | Radiation Transport

logo: wkubinski.jpg   # optional if you add a photo

show_downloads: false

github:
  is_project_page: false

author:
  name: Wojciech Kubinski
  email: w.r.kubinski@gmail.com
  location: Oxford, United Kingdom

plugins:
  - jekyll-seo-tag

markdown: kramdown
